-- Migration: Insert 25 Default Recipes
-- Fixed version with correct column names and proper JSONB casting
-- Note: Using a system UUID for default recipes (can be updated to a real admin user later)

INSERT INTO recipes (user_id, title, description, dietary_type, difficulty, prep_time, cook_time, servings, calories, protein, carbs, fats, fiber, ingredients, instructions, tags, allergens, health_benefits, image_url, is_public, is_ai_generated) VALUES
('00000000-0000-0000-0000-000000000000', 'Grilled Chicken Quinoa Bowl', 'Protein-packed bowl with grilled chicken, fluffy quinoa, roasted vegetables, and a zesty lemon tahini dressing.', 'Gluten-Free', 'Easy', 15, 25, 2, 450, 38, 42, 14, 8, '[{"item":"Chicken breast","amount":"300g","notes":"boneless, skinless"},{"item":"Quinoa","amount":"1 cup","notes":"uncooked"},{"item":"Bell peppers","amount":"2","notes":"mixed colors"},{"item":"Cherry tomatoes","amount":"1 cup"},{"item":"Tahini","amount":"2 tbsp"},{"item":"Lemon juice","amount":"2 tbsp"},{"item":"Olive oil","amount":"1 tbsp"}]'::jsonb, '[{"step":1,"instruction":"Cook quinoa according to package instructions."},{"step":2,"instruction":"Season chicken with salt, pepper, and herbs. Grill for 6-7 minutes per side."},{"step":3,"instruction":"Roast bell peppers and tomatoes at 400°F for 15 minutes."},{"step":4,"instruction":"Mix tahini, lemon juice, and water to make dressing."},{"step":5,"instruction":"Assemble bowls with quinoa, sliced chicken, vegetables, and drizzle with dressing."}]'::jsonb, ARRAY['High Protein','Gluten-Free','Meal Prep'], ARRAY['sesame'], ARRAY['High in protein','Rich in fiber','Complete amino acids'], 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80', true, false),

('00000000-0000-0000-0000-000000000000', 'Avocado Toast with Poached Eggs', 'Classic breakfast with creamy avocado, perfectly poached eggs, and a sprinkle of chili flakes on whole grain toast.', 'Vegetarian', 'Easy', 5, 10, 2, 320, 15, 28, 18, 10, '[{"item":"Whole grain bread","amount":"4 slices"},{"item":"Avocado","amount":"2","notes":"ripe"},{"item":"Eggs","amount":"4","notes":"fresh"},{"item":"Cherry tomatoes","amount":"1 cup","notes":"halved"},{"item":"Chili flakes","amount":"1 tsp"},{"item":"Salt and pepper","amount":"to taste"}]'::jsonb, '[{"step":1,"instruction":"Toast bread slices until golden brown."},{"step":2,"instruction":"Mash avocados with salt, pepper, and lemon juice."},{"step":3,"instruction":"Poach eggs in simmering water with vinegar for 3-4 minutes."},{"step":4,"instruction":"Spread avocado on toast, top with poached eggs."},{"step":5,"instruction":"Garnish with cherry tomatoes, chili flakes, and black pepper."}]'::jsonb, ARRAY['Breakfast','Quick','Vegetarian'], ARRAY['eggs','gluten'], ARRAY['Healthy fats','Rich in vitamins','Good fiber source'], 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80', true, false),

('00000000-0000-0000-0000-000000000000', 'Mediterranean Chickpea Salad', 'Refreshing salad with chickpeas, cucumber, tomatoes, feta cheese, and olives in a lemon herb dressing.', 'Vegetarian', 'Easy', 15, 0, 4, 280, 12, 32, 12, 9, '[{"item":"Chickpeas","amount":"2 cans","notes":"drained and rinsed"},{"item":"Cucumber","amount":"2","notes":"diced"},{"item":"Cherry tomatoes","amount":"2 cups","notes":"halved"},{"item":"Feta cheese","amount":"150g","notes":"crumbled"},{"item":"Kalamata olives","amount":"1/2 cup"},{"item":"Red onion","amount":"1/2","notes":"thinly sliced"},{"item":"Olive oil","amount":"3 tbsp"},{"item":"Lemon juice","amount":"2 tbsp"},{"item":"Fresh herbs","amount":"1/4 cup","notes":"parsley and mint"}]'::jsonb, '[{"step":1,"instruction":"Combine chickpeas, cucumber, tomatoes, and onion in a large bowl."},{"step":2,"instruction":"Add olives and feta cheese."},{"step":3,"instruction":"Whisk together olive oil, lemon juice, salt, and pepper."},{"step":4,"instruction":"Pour dressing over salad and toss gently."},{"step":5,"instruction":"Garnish with fresh herbs and serve chilled."}]'::jsonb, ARRAY['Vegan Option','No Cook','Mediterranean'], ARRAY['dairy'], ARRAY['Plant-based protein','Heart-healthy fats','Rich in antioxidants'], 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80', true, false),

('00000000-0000-0000-0000-000000000000', 'Salmon Teriyaki with Broccoli', 'Glazed salmon fillet with homemade teriyaki sauce, served with steamed broccoli and sesame seeds.', 'Pescatarian', 'Medium', 10, 20, 2, 380, 42, 18, 16, 4, '[{"item":"Salmon fillets","amount":"2","notes":"150g each"},{"item":"Broccoli","amount":"2 cups","notes":"florets"},{"item":"Soy sauce","amount":"3 tbsp"},{"item":"Honey","amount":"2 tbsp"},{"item":"Ginger","amount":"1 tbsp","notes":"grated"},{"item":"Garlic","amount":"2 cloves","notes":"minced"},{"item":"Sesame seeds","amount":"1 tbsp"}]'::jsonb, '[{"step":1,"instruction":"Mix soy sauce, honey, ginger, and garlic for teriyaki sauce."},{"step":2,"instruction":"Marinate salmon in half the sauce for 10 minutes."},{"step":3,"instruction":"Pan-sear salmon for 4-5 minutes per side."},{"step":4,"instruction":"Steam broccoli for 5-6 minutes until tender-crisp."},{"step":5,"instruction":"Brush salmon with remaining sauce and garnish with sesame seeds."}]'::jsonb, ARRAY['High Protein','Omega-3','Asian'], ARRAY['fish','soy','sesame'], ARRAY['Rich in Omega-3','High quality protein','Vitamin D'], 'https://images.unsplash.com/photo-1580959375944-0b80a7a8b6da?w=800&q=80', true, false),

('00000000-0000-0000-0000-000000000000', 'Greek Yogurt Parfait', 'Layered parfait with Greek yogurt, fresh berries, granola, and a drizzle of honey.', 'Vegetarian', 'Easy', 5, 0, 2, 250, 18, 35, 6, 5, '[{"item":"Greek yogurt","amount":"2 cups","notes":"plain, low-fat"},{"item":"Mixed berries","amount":"1.5 cups","notes":"strawberries, blueberries, raspberries"},{"item":"Granola","amount":"1/2 cup"},{"item":"Honey","amount":"2 tbsp"},{"item":"Chia seeds","amount":"1 tbsp","notes":"optional"}]'::jsonb, '[{"step":1,"instruction":"Layer Greek yogurt in glasses or bowls."},{"step":2,"instruction":"Add a layer of mixed berries."},{"step":3,"instruction":"Sprinkle granola over berries."},{"step":4,"instruction":"Repeat layers until glasses are filled."},{"step":5,"instruction":"Drizzle with honey and top with chia seeds."}]'::jsonb, ARRAY['Breakfast','Quick','No Cook'], ARRAY['dairy','gluten'], ARRAY['Probiotics','Antioxidants','High in protein'], 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80', true, false);

-- Successfully inserts 5 test recipes
-- Ready to expand to all 25 recipes
